### ISSUE TITLE
Readme contains "Example Usage" code for the wrong project.

### ISSUE THREAD

**Issue by unclejessiespano** [kevinem/adobe-sign-laravel#1]
The code examples in the "Example Usage" section are for your Laravel Places repo, not the adobe sign repo.

Can you provide similar code samples for the adobe-sign-laravel repo?

**Comment by hlorofos** [comment]
+1

**Comment by kevinem** [comment]
Sorry about that. I've updated the readme with a few examples. The rest of of the methods that are available should be within the documentation of adobe's website at https://secure.na1.echosign.com/public/docs/restapi/v5.
